
jobs:
  - job: testingDownloadPipelineArtifact
    displayName: 'Producing artifacts'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: |
          cp *  $BUILD_ARTIFACTSTAGINGDIRECTORY
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'test-pipe'
          targetPath: '$(Build.ArtifactStagingDirectory)'
